ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'


Vagrant.configure("2") do |config|

  config.vm.synced_folder "c:/introduction-docker-workshop/share-with-container", "/host_share"
  config.vm.synced_folder "c:/introduction-docker-workshop/software", "/software"

  config.vm.define "desktop-puppet-container" do |m|
    m.vm.provider :docker do |d| 
      d.build_dir = "./docker"
      d.cmd = ["ping", "-c 2551", "127.0.0.1"] 
	  d.name = 'desktop-puppet-container'
      d.vagrant_machine = "dockerdesktophost"
      d.vagrant_vagrantfile = "../DockerHost/DockerDesktopHostVagrantfile" 
      d.remains_running = true 

	  end
  end 

  # note: after docker completes
  # get into the container
  # docker exec -it <container id> bash
  # and run Puppet:
  # puppet apply --modulepath=/puppet/modules /puppet/manifests/base.pp
  
  
  config.vm.define "desktop-container" do |m|
  
    m.vm.provider "docker" do |master|
        master.image = "my-desktop-image:version1"
		master.cmd=["tail", "--f", "/dev/null"] ## to keep container running - see http://stackoverflow.com/questions/30209776/docker-container-will-automatically-stop-after-docker-run-d 		
	    master.name = 'desktop-container'
        master.vagrant_machine = "dockerdesktophost"
        master.vagrant_vagrantfile = "../DockerHost/DockerDesktopHostVagrantfile" 
        master.remains_running = true 
	end
  end
  
end  
